# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vn-pickup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AWS
  pod 'AWSCore', '~> 2.9.6'
  pod 'AWSAppSync', ' ~> 2.13.0'
  
  # Used for interacting with keyboard
  pod 'IQKeyboardManagerSwift'
  
end
